wifi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import *
from core.utils import calc
from core.views import *
from django.contrib.staticfiles import views




urlpatterns = [
    url(r'^$', SubscriptionView.as_view(), name='home'),
    #url(r'^phone/(?P<id>[-\w]+)/$', phone, name='phone'),
    url(r'^phone/(?P<pk>[-\w]+)/', PointWifiPhoneDetail.as_view(), name='phone'),
    url(r'^chat/(?P<pk>[-\w]+)/', ChatDetail.as_view(), name='chat'),
    url(r'^sub/add/', sub_add, name='sub_add'),
    url(r'^sub/(?P<id>.*)/delete/$', sub_delete, name='sub_delete'),
    url(r'^sub/(?P<id>.*)/edit/$', sub_edit, name='sub_edit'),
    url(r'^sub/(?P<id>.*)/copy/$', sub_copy, name='sub_copy'),

    url(r'^add/messages/(?P<wifi>.*)/(?P<id>.*)/$', add_messages, name='add_messages'),

    url(r'^create/user/', create_account, name='create_account'),
    url(r'^login/', my_login, name='my_login'),

    url(r'^get/messages', receive_ms, name='receive_ms'),

    url(r'^test', calc, name='test'),

    url(r'^forms', PopupView.as_view(), name='forms'),

    url(r'^nexmo/', include('nexmo.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
]

app/core/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from accounts import UserProfile


class BaseModel(models.Model):
    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


"""
#
# Account
#
"""
class Account(BaseModel):
    user = models.ForeignKey(UserProfile, null=True, related_name='user_account')
    phone = models.CharField('phone', max_length=15)

"""
#
# PointWifi
#
"""
class PointWifi(BaseModel):
    user = models.ForeignKey(UserProfile, null=True, related_name='user_b_wifi')
    name = models.CharField('name', max_length=255)

"""
#
# Messages
#
"""


class Messages(BaseModel):
    STATUS_MES = (
    (0, 'Успешно доставлено!'),
    (1, 'You have exceeded the submission capacity allowed on this account, please back-off and retry'),
    (2, 'Your request is incomplete and missing some mandatory parameters'),
    (3, 'The value of one or more parameters is invalid'),
    (4, 'The api_key / api_secret you supplied is either invalid or disabled'),
    (5, 'An error has occurred in the Nexmo platform whilst processing this message'),
    (6, 'The Nexmo platform was unable to process this message, for example, an un-recognized number prefix or the '
        'number is not whitelisted if your account is new'),
    (7, 'The number you are trying to submit to is blacklisted and may not receive messages'),
    (8, 'The api_key you supplied is for an account that has been barred from submitting messages'),
    (9, 'Your pre-pay account does not have sufficient credit to process this message'),
    (11, 'This account is not provisioned for REST submission, you should use SMPP instead'),
    (12, 'Applies to Binary submissions, where the length of the UDH and the message body combined exceed 140 octets'),
    (13, 'Message was not submitted because there was a communication failure'),
    (14, 'Message was not submitted due to a verification failure in the submitted signature'),
    (15, 'The sender address (from parameter) was not allowed for this message. Restrictions may apply depending '
         'on the destination see ou'),
    (16, 'The ttl parameter values is invalid'),
    (19, 'Your request makes use of a facility that is not enabled on your account'),
    (20, 'The message class value supplied was out of range (0 - 3)'),
    )
    base_account = models.ForeignKey(UserProfile, null=True, related_name='user_messages')
    account = models.ForeignKey(Account, null=True, related_name='account_messages')
    wifi = models.ForeignKey(PointWifi, null=True, related_name='wifi_messages')
    text = models.CharField('Text', max_length=560, blank=True)
    admin = models.BooleanField(default=False)
    id_ms = models.CharField('ID', blank=True, null=True, max_length=250)

    status = models.IntegerField('Статус', default=0, choices=STATUS_MES)

"""
#
# Entered
#
"""
class Entered(BaseModel):
    user = models.ForeignKey(UserProfile, null=True, related_name='base_entered_messages')
    wifi = models.ForeignKey(PointWifi, null=True, related_name='wifi_entered')
    account = models.ForeignKey(Account, null=True, related_name='entered_messages')


"""
#
# Subscriptions (pattern)
#
"""
RUN_SUB_CHOICES = (
    (1, 'Не рассылать'),
    (2, 'Разослать 1 раз'),
    (3, 'Рассылка по условиям'),
)




class Subscriptions(models.Model):
   #condition = Условие расcылки
   account = models.ForeignKey(UserProfile, null=True, related_name='user_subs')

   title = models.CharField('Имя шаблона', max_length=255)
   content = models.CharField('Текст сообщения', max_length=560)
   phone = models.IntegerField('Подпись отправителя')

   run_sub = models.IntegerField('Выполнять рассылку периодически по фильтру',default=1, choices=RUN_SUB_CHOICES)

   now = models.BooleanField('Сейчас', default=False, blank=True)

   start_at = models.DateTimeField('Дата начала рассылки', blank=True, null=True)

   send = models.BooleanField('Отправлено', default=False, blank=True)

CONDITION_CHOICES = (
    (1, 'Равно'),
    (2, 'Не равно'),
    (3, 'Больше'),
    (4, 'Меньше'),
    (5, 'Больше или равно'),
    (6, 'Меньше или равно'),
    (7, 'Изменено'),
)

PLUSMINUS_CHOICES = (
    (1, '+'),
    (2, '-')
)

DATES_CHOICES = (
    (1, 'Дней'),
    (2, 'Месяцев'),
    (3, 'Лет'),
    (4, 'Часов'),
    (5, 'Минут'),
)

CHOICES = (
    (1, 'И'),
    (2, 'ИЛИ')
)


class Condition(models.Model):
    condition = models.IntegerField('Сравнение',default=1, choices=CONDITION_CHOICES)
    location = models.IntegerField(default=1, blank=True)
    choice = models.IntegerField('Выбор сравнения', default=None, null=True, blank=True, choices=CHOICES)

    class Meta:
        abstract = True

class ConditionTime(Condition):
    start_at = models.DateTimeField('Дата отчета', blank=True, null=True)
    plusminus = models.IntegerField('Плюс минус',default=1, choices=PLUSMINUS_CHOICES)
    count_time = models.IntegerField(default=0, blank=True)
    dates = models.IntegerField('Выбор дат',default=1, choices=DATES_CHOICES)

class ConditionPoint(Condition):
    wifi = models.ForeignKey(PointWifi, blank=True, null=True, related_name='condition__point__wifi')

class ConditionCount(Condition):
    count = models.IntegerField('Количеств посещений', default=0)

class ConditionGroups(models.Model):
    subscription = models.ForeignKey(Subscriptions, blank=False, null=True, related_name='groups__sub__condition')
    time = models.ManyToManyField(ConditionTime)
    point = models.ManyToManyField(ConditionPoint)
    count = models.ManyToManyField(ConditionCount)

templates/base.html
{% extends 'bootstrap.html' %}

{% load url from future %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <div class="container">

        {% block content %}(no content){% endblock %}
    </div>
{% endblock %}

templates/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load static from staticfiles %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

{% block bootstrap3_extra_head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.css' %}">
{% endblock %}


{% block bootstrap3_extra_script %}
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.datetimepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui-sliderAccess.js' %}"></script>
<script type="text/javascript" src="{% static 'js/i18n/jquery-ui-timepicker-ru.js' %}"></script>
<script type="text/javascript" src="{% static 'js/condition.js' %}"></script>
<script type="text/javascript" src="{% static 'js/moment-with-locales.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-modal.js' %}"></script>
<script>
(function() {
    $("#id_start_at").datetimepicker({
    format: "y-m-d H:i",
        lang:'ru'
    });
    /*$(".start_at").datetimepicker({
    dateFormat: "yy-mm-dd",
    timeFormat: "hh:mm"
    });*/
})();
    </script>
    <script>



    $(function(){
        condition = new Condition();
    })
</script>
<script>
(function() {
    $('#conditionModal').modal('hide')
})();
$(function() {
    $('.delete_condition').on('click',function() {
         $($(this).parents().get(1)).remove();
    });
});
</script>

{% endblock %}

templates/form.html
<div  style="display: none;" class="condition__block__pattern form-inline form-condition">
        <label class="control-label">Условия</label>
        <div class="condition condition-time pattern">
        <div class="form-group">
            <div onClick="delCondition($(this))" data-type="time" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-time-0-position" type="number" value="1">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Время авторизации">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom time" id="id_form-0-run_sub" name="condition-time-0-time" title="">
                 <option value="1" selected>Время авторизации</option>
                 <option value="2">Точка доступа</option>
                 <option value="3">Кол-во посещений</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom tcondition" id="id_form-0-run_sub" name="condition-time-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
                <option value="3">Больше</option>
                <option value="4">Меньше</option>
                <option value="5">Больше или равно</option>
                <option value="6">Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom start_at"  name="condition-time-0-start_at" placeholder="Текущее время" title="" type="text">
        </div>
        <div class="form-group">
            <select class="form-control-custom plusminus" id="id_form-0-run_sub" name="condition-time-0-plusminus" title="">
                <option value="1">+</option>
                <option value="2">-</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom count_time" id="id_form-0-date" name="condition-time-0-count_time" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom dates" id="id_form-0-run_sub" name="condition-time-0-dates" title="">
                <option value="1">Дней</option>
                <option value="2">Месяцев</option>
                <option value="3">Лет</option>
                <option value="4">Часов</option>
                <option value="5">Минут</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-time-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>

        <div class="condition condition-point pattern">
        <div class="form-group">
            <div onClick="delCondition($(this))" data-type="point" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-point-0-position" type="number" value="2">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Точка доступа">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom point" id="id_form-0-run_sub" name="condition-point-0-point" title="">
                 <option value="2" selected>Точка доступа</option>
                 <option value="1">Время авторизации</option>
                 <option value="3">Кол-во посещений</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom pcondition" id="id_form-0-run_sub" name="condition-point-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom wifi" id="id_form-0-run_sub" name="condition-point-0-wifi" title="">
                {% for wi in wifi %}
                    <option value="{{ wi.id }}">{{ wi.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-point-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>
        <div class="condition condition-count pattern">
        <div class="form-group">
            <div onClick="delCondition($(this))" data-type="count" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-count-0-position" type="number" value="3">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Кол-во посещений">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom count" id="id_form-0-run_sub" name="condition-count-0-count" title="">
                 <option value="3" selected>Кол-во посещений</option>
                 <option value="1">Время авторизации</option>
                 <option value="2">Точка доступа</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom ccondition" id="id_form-0-run_sub" name="condition-count-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
                <option value="3">Больше</option>
                <option value="4">Меньше</option>
                <option value="5">Больше или равно</option>
                <option value="6">Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom mcount" id="id_form-0-date" name="condition-count-0-mcount" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-count-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>
        </div>

templates/form_.html
<div style="display:none" class="condition__block form-inline form-condition">
        <label class="control-label">Условия</label>
        <div class="condition condition-time">
        <div class="form-group">
            <div data-type="time" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-time-0-position" type="number" value="1">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Время авторизации">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom time" id="id_form-0-run_sub" name="condition-time-0-time" title="">
                 <option value="1" selected>Время авторизации</option>
                 <option value="2">Точка доступа</option>
                 <option value="3">Кол-во посещений</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom tcondition" id="id_form-0-run_sub" name="condition-time-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
                <option value="3">Больше</option>
                <option value="4">Меньше</option>
                <option value="5">Больше или равно</option>
                <option value="6">Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom start_at"  name="condition-time-0-start_at" value="Текущее время" readonly placeholder="Текущее время" title="" type="text">
        </div>
        <div class="form-group">
            <select class="form-control-custom plusminus" id="id_form-0-run_sub" name="condition-time-0-plusminus" title="">
                <option value="1">+</option>
                <option value="2">-</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom count_time" id="id_form-0-date" name="condition-time-0-count_time" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom dates" id="id_form-0-run_sub" name="condition-time-0-dates" title="">
                <option value="1">Дней</option>
                <option value="2">Месяцев</option>
                <option value="3">Лет</option>
                <option value="4">Часов</option>
                <option value="5">Минут</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-time-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>

        <div class="condition condition-point">
        <div class="form-group">
            <div data-type="point" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-point-0-position" type="number" value="2">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Точка доступа">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom point" id="id_form-0-run_sub" name="condition-point-0-point" title="">
                 <option value="2" selected>Точка доступа</option>
                 <option value="1">Время авторизации</option>
                 <option value="3">Кол-во посещений</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom pcondition" id="id_form-0-run_sub" name="condition-point-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom wifi" id="id_form-0-run_sub" name="condition-point-0-wifi" title="">
                {% for wi in wifi %}
                    <option value="{{ wi.id }}">{{ wi.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-point-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>
        <div class="condition condition-count">
        <div class="form-group">
            <div data-type="count" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-count-0-position" type="number" value="3">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Кол-во посещений">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom count" id="id_form-0-run_sub" name="condition-count-0-count" title="">
                 <option value="3" selected>Кол-во посещений</option>
                 <option value="1">Время авторизации</option>
                 <option value="2">Точка доступа</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom ccondition" id="id_form-0-run_sub" name="condition-count-0-condition" title="">
                <option value="1">Равно</option>
                <option value="2">Не равно</option>
                <option value="3">Больше</option>
                <option value="4">Меньше</option>
                <option value="5">Больше или равно</option>
                <option value="6">Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom mcount" id="id_form-0-date" name="condition-count-0-mcount" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-count-0-choice" title="">
                <option value="1">И</option>
                <option value="2">ИЛИ</option>
            </select>
        </div>
        </div>
        </div>

        <button style="display:none" type="button" class="btn btn-add-condition btn-primary btn-xs" data-toggle="modal" data-target="#conditionModal">
               Добавить условие
        </button>
        <p></p>

templates/form_edit.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/form_edit_.html
<div  class="condition__block form-inline form-condition">
        <label class="control-label">Условия</label>
{% for order in orders %}

        {% if order.plusminus %}

        <div class="condition condition-time">
        <div class="form-group">
            <div data-type="time" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-time-0-position" type="number" value="{{ order.location }}">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Время авторизации">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom time" id="id_form-0-run_sub" name="condition-time-0-time" title="">
                 <option value="1" selected>Время авторизации</option>
                 <option value="2">Точка доступа</option>
                 <option value="3">Кол-во посещений</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom tcondition" id="id_form-0-run_sub" name="condition-time-0-condition" title="">
                <option value="1" {% if order.condition == 1 %}selected{% endif %}>Равно</option>
                <option value="2" {% if order.condition == 2 %}selected{% endif %}>Не равно</option>
                <option value="3" {% if order.condition == 3 %}selected{% endif %}>Больше</option>
                <option value="4" {% if order.condition == 4 %}selected{% endif %}>Меньше</option>
                <option value="5" {% if order.condition == 5 %}selected{% endif %}>Больше или равно</option>
                <option value="6" {% if order.condition == 6 %}selected{% endif %}>Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom start_at" readonly name="condition-time-0-start_at" value="Текущее время" placeholder="Текущее время" title="" type="text">
        </div>
        <div class="form-group">
            <select class="form-control-custom plusminus" id="id_form-0-run_sub" name="condition-time-0-plusminus" title="">
                <option value="1" {% if order.plusminus == 1 %}selected{% endif %}>+</option>
                <option value="2" {% if order.plusminus == 2 %}selected{% endif %}>-</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom count_time" id="id_form-0-date" value="{{ order.count_time }}" name="condition-time-0-count_time" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom dates" id="id_form-0-run_sub" name="condition-time-0-dates" title="">
                <option value="1" {% if order.dates == 1 %}selected{% endif %}>Дней</option>
                <option value="2" {% if order.dates == 2 %}selected{% endif %}>Месяцев</option>
                <option value="3" {% if order.dates == 3 %}selected{% endif %}>Лет</option>
                <option value="4" {% if order.dates == 4 %}selected{% endif %}>Часов</option>
                <option value="5" {% if order.dates == 5 %}selected{% endif %}>Минут</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-time-0-choice" title="">
                <option value="1" {% if order.choice == 1 %}selected{% endif %}>И</option>
                <option value="2" {% if order.choice == 2 %}selected{% endif %}>ИЛИ</option>
            </select>
        </div>
        </div>

        {% endif %}

        {% if order.wifi %}

        <div class="condition condition-point">
        <div class="form-group">
            <div data-type="point" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-point-0-position" type="number" value="{{ order.location }}">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Точка доступа">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom point" id="id_form-0-run_sub" name="condition-point-0-point" title="">
                 <option value="2" selected>Точка доступа</option>
                 <option value="1">Время авторизации</option>
                 <option value="3">Кол-во посещений</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom pcondition" id="id_form-0-run_sub" name="condition-point-0-condition" title="">
                <option value="1" {% if order.condition == 1 %}selected{% endif %}>Равно</option>
                <option value="2" {% if order.condition == 2 %}selected{% endif %}>Не равно</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom wifi" id="id_form-0-run_sub" name="condition-point-0-wifi" title="">
                {% for wi in wifi %}
                    <option value="{{ wi.id }}" {% if wifi == order.wifi %}selected{% endif %}>{{ wi.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-0-run_sub" name="condition-point-0-choice" title="">
                <option value="1" {% if order.choice == 1 %}selected{% endif %}>И</option>
                <option value="2" {% if order.choice == 2 %}selected{% endif %}>ИЛИ</option>
            </select>
        </div>
        </div>

        {% endif %}

        {% if order.count %}

        <div class="condition condition-count">
        <div class="form-group">
            <div data-type="count" class="delete_condition">X</div>
        </div>
        <input class="position" style="display:none" name="condition-count-{{ forloop.counter0 }}-position" type="number" value="{{ order.location }}">
        <div class="form-group">
            <input readonly class="form-control-custom" type="text" value="Кол-во посещений">
        </div>
        <div style="display: none" class="form-group">
            <select class="form-control-custom count" id="id_form-{{ forloop.counter0 }}-run_sub" name="condition-count-{{ forloop.counter0 }}-count" title="">
                 <option value="3" selected>Кол-во посещений</option>
                 <option value="1">Время авторизации</option>
                 <option value="2">Точка доступа</option>
            </select>

        </div>
        <div class="form-group">
            <select class="form-control-custom ccondition" id="id_form-{{ forloop.counter0 }}-run_sub" name="condition-count-{{ forloop.counter0 }}-condition" title="">
                <option value="1" {% if order.condition == 1 %}selected{% endif %}>Равно</option>
                <option value="2" {% if order.condition == 2 %}selected{% endif %}>Не равно</option>
                <option value="3" {% if order.condition == 3 %}selected{% endif %}>Больше</option>
                <option value="4" {% if order.condition == 4 %}selected{% endif %}>Меньше</option>
                <option value="5" {% if order.condition == 5 %}selected{% endif %}>Больше или равно</option>
                <option value="6" {% if order.condition == 6 %}selected{% endif %}>Меньше или равно</option>
            </select>
        </div>
        <div class="form-group">
            <input class="form-control-custom mcount" id="id_form-{{ forloop.counter0 }}-date" name="condition-count-{{ forloop.counter0 }}-mcount" value="{{ order.count }}" title="" type="number">
        </div>
        <div class="form-group">
            <select class="form-control-custom choice" id="id_form-{{ forloop.counter0 }}-run_sub" name="condition-count-{{ forloop.counter0 }}-choice" title="">
                <option value="1" {% if order.choice == 1 %}selected{% endif %}>И</option>
                <option value="2" {% if order.choice == 2 %}selected{% endif %}>ИЛИ</option>
            </select>
        </div>
        </div>

        {% endif %}

{% endfor %}
</div>

        <button type="button" class="btn btn-add-condition btn-primary btn-xs" data-toggle="modal" data-target="#conditionModal">
               Добавить условие
        </button>
        <p></p>

templates/home.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% include 'subscription.html' %}
    {% else %}
        {% include 'none.html' %}
    {% endif %}

{% endblock %}

templates/none.html
<div class="center__block">
<form role="form" class="ajaxify-form create_list_form" action="{% url 'create_account' %}" data-submit="CreateUser" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Номер телефона</label>
    <input type="number" class="form-control" name="phone" placeholder="Введите номер телефона">
    <p>Например: <b>9998887766</b></p>
  </div>
    <div class="nocode">
  <button type="submit" class="btn btn-primary">Запросить пароль</button>
  <p  class="btn btn-success have__pass">У меня уже есть пароль</p>
    </div>
    <div style="display: none" class="code">
  <div class="form-group">
    <label for="exampleInputEmail1">Пароль</label>
    <input type="text" class="form-control" name="code" placeholder="Введите пароль">
  </div>
  <button type="submit" class="btn btn-default">Войти</button>
    </div>
</form>
</div>